// Parity fixture: Layers' menu bar expressed as a <menu-bar> config.
// Menu tree, labels, ids, shortcut hints, submenu taxonomy (incl. the full
// 12-category / 75-effect filter tree, generated byte-exact from the app
// markup), and state gating transcribed from the live app
// (public/index.html + app.js state managers).

export default function layersConfig() {
    window.__parity = {
        calls: [],
        state: {
            canUndo: false,
            canRedo: false,
            hasSelection: false,
            selectedLayerIds: [],       // [] | ['a'] | ['a','b']
            activeLayerHasMask: false,
            activeLayerIsMedia: false,
            collab: true,
            zoom: 'fit',                // fit | 50 | 100 | 200
            playing: true,
        },
    }
    const s = window.__parity.state
    const act = id => () => window.__parity.calls.push(id)
    const oneSelected = () => s.selectedLayerIds.length === 1

    return {
        ariaLabel: 'Layers menu',
        regions: {
            left: [
                {
                    type: 'menu',
                    id: 'logoMenu',
                    trigger: {
                        html: '<svg id="logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" fill="currentColor" aria-hidden="true" focusable="false"><path d="M840 5478h-100z"/></svg>',
                        ariaLabel: 'Layers menu',
                    },
                    items: [
                        { id: 'welcomeMenuItem', label: 'welcome to Layers...', onSelect: act('welcomeMenuItem') },
                        { id: 'aboutMenuItem', label: 'about Layers', onSelect: act('aboutMenuItem') },
                        { id: 'settingsMenuItem', label: 'settings...', onSelect: act('settingsMenuItem') },
                    ],
                },
                {
                    type: 'menu',
                    trigger: { label: 'file' },
                    items: [
                        { id: 'newMenuItem', label: 'new...', onSelect: act('newMenuItem') },
                        { id: 'newFromClipboardMenuItem', label: 'new from clipboard', onSelect: act('newFromClipboardMenuItem') },
                        { id: 'openMenuItem', label: 'open...', onSelect: act('openMenuItem') },
                        { type: 'separator' },
                        { id: 'saveProjectMenuItem', label: 'save project', onSelect: act('saveProjectMenuItem') },
                        { id: 'saveProjectAsMenuItem', label: 'save project as...', onSelect: act('saveProjectAsMenuItem') },
                        { id: 'loadProjectMenuItem', label: 'load project...', onSelect: act('loadProjectMenuItem') },
                        { type: 'separator' },
                        { id: 'savePngMenuItem', label: 'quick save as png', onSelect: act('savePngMenuItem') },
                        { id: 'saveJpgMenuItem', label: 'quick save as jpg', onSelect: act('saveJpgMenuItem') },
                        { type: 'separator' },
                        { id: 'exportImageMenuItem', label: 'export image...', onSelect: act('exportImageMenuItem') },
                        { id: 'exportVideoMenuItem', label: 'export video clip...', onSelect: act('exportVideoMenuItem') },
                        { type: 'separator', id: 'onlineCollabMenuSeparator', hidden: () => !s.collab },
                        { id: 'goOnlineMenuItem', label: 'go online...', hidden: () => !s.collab, onSelect: act('goOnlineMenuItem') },
                    ],
                },
                {
                    type: 'menu',
                    trigger: { label: 'edit' },
                    items: [
                        { id: 'undoMenuItem', label: 'undo', shortcut: '⌘Z', disabled: () => !s.canUndo, onSelect: act('undoMenuItem') },
                        { id: 'redoMenuItem', label: 'redo', shortcut: '⌘⇧Z', disabled: () => !s.canRedo, onSelect: act('redoMenuItem') },
                        { type: 'separator' },
                        { id: 'copyImageMenuItem', label: 'copy image', onSelect: act('copyImageMenuItem') },
                        { id: 'pasteImageMenuItem', label: 'paste image', shortcut: '⌘V', onSelect: act('pasteImageMenuItem') },
                    ],
                },
        {
            type: 'menu',
            id: 'imageMenu',
            trigger: { label: 'image' },
            items: [
                { id: 'autoLevelsMenuItem', label: 'auto levels', onSelect: act('autoLevelsMenuItem') },
                { id: 'autoContrastMenuItem', label: 'auto contrast', onSelect: act('autoContrastMenuItem') },
                { id: 'autoWhiteBalanceMenuItem', label: 'auto white balance', onSelect: act('autoWhiteBalanceMenuItem') },
                { type: 'separator' },
                { type: 'submenu', classes: 'has-submenu', attrs: { 'data-submenu': 'tone' }, label: 'tone', items: [
                    { label: "brightness/contrast", attrs: { 'data-effect': 'filter/adjust' }, onSelect: () => window.__parity.calls.push('effect:filter/adjust') },
                    { label: "levels", attrs: { 'data-effect': 'filter/smoothstep' }, onSelect: () => window.__parity.calls.push('effect:filter/smoothstep') },
                    { label: "posterize", attrs: { 'data-effect': 'filter/posterize' }, onSelect: () => window.__parity.calls.push('effect:filter/posterize') },
                    { label: "threshold", attrs: { 'data-effect': 'filter/threshold' }, onSelect: () => window.__parity.calls.push('effect:filter/threshold') },
                ] },
                { type: 'submenu', classes: 'has-submenu', attrs: { 'data-submenu': 'color' }, label: 'color', items: [
                    { label: "hue/saturation", attrs: { 'data-effect': 'filter/adjust' }, onSelect: () => window.__parity.calls.push('effect:filter/adjust') },
                    { label: "color grading", attrs: { 'data-effect': 'filter/grade' }, onSelect: () => window.__parity.calls.push('effect:filter/grade') },
                    { label: "tint", attrs: { 'data-effect': 'filter/tint' }, onSelect: () => window.__parity.calls.push('effect:filter/tint') },
                    { label: "color replace", attrs: { 'data-effect': 'filter/colorReplace' }, onSelect: () => window.__parity.calls.push('effect:filter/colorReplace') },
                    { label: "invert", attrs: { 'data-effect': 'filter/invert' }, onSelect: () => window.__parity.calls.push('effect:filter/invert') },
                    { label: "gradient palette", attrs: { 'data-effect': 'filter/tetraColorArray' }, onSelect: () => window.__parity.calls.push('effect:filter/tetraColorArray') },
                ] },
                { type: 'separator' },
                { id: 'cropToSelectionMenuItem', label: 'crop to selection', disabled: () => !s.hasSelection, onSelect: act('cropToSelectionMenuItem') },
                { type: 'separator' },
                { id: 'imageSizeMenuItem', label: 'image size...', onSelect: act('imageSizeMenuItem') },
                { id: 'canvasSizeMenuItem', label: 'canvas size...', onSelect: act('canvasSizeMenuItem') },
            ],
        },
                {
                    type: 'menu',
                    trigger: { label: 'layer' },
                    items: [
                        { id: 'duplicateLayerMenuItem', label: 'duplicate layer', disabled: () => !oneSelected(), onSelect: act('duplicateLayerMenuItem') },
                        { id: 'deleteLayerMenuItem', label: 'delete layer', disabled: () => !oneSelected(), onSelect: act('deleteLayerMenuItem') },
                        { type: 'separator' },
                        { id: 'flipHMenuItem', label: 'flip horizontal', disabled: () => !(oneSelected() && s.activeLayerIsMedia), onSelect: act('flipHMenuItem') },
                        { id: 'flipVMenuItem', label: 'flip vertical', disabled: () => !(oneSelected() && s.activeLayerIsMedia), onSelect: act('flipVMenuItem') },
                        { type: 'separator' },
                        { id: 'addLayerMaskMenuItem', label: 'add layer mask', disabled: () => !oneSelected() || s.activeLayerHasMask, onSelect: act('addLayerMaskMenuItem') },
                        { id: 'deleteLayerMaskMenuItem', label: 'delete layer mask', disabled: () => !(oneSelected() && s.activeLayerHasMask), onSelect: act('deleteLayerMaskMenuItem') },
                        { type: 'separator' },
                        {
                            id: 'layerActionMenuItem',
                            // true 3-way dynamic label
                            label: () => s.selectedLayerIds.length === 0 ? 'flatten image'
                                : s.selectedLayerIds.length === 1 ? 'rasterize layer' : 'flatten layers',
                            disabled: () => s.selectedLayerIds.length === 1 && s.activeLayerIsMedia,
                            onSelect: act('layerActionMenuItem'),
                        },
                        { type: 'separator' },
                        { id: 'deselectAllLayersMenuItem', label: 'deselect all layers', onSelect: act('deselectAllLayersMenuItem') },
                    ],
                },
                {
                    type: 'menu',
                    trigger: { label: 'select' },
                    items: [
                        { id: 'selectAllMenuItem', label: 'select all', shortcut: '⌘A', onSelect: act('selectAllMenuItem') },
                        { id: 'selectNoneMenuItem', label: 'select none', shortcut: '⌘D', disabled: () => !s.hasSelection, onSelect: act('selectNoneMenuItem') },
                        { id: 'selectInverseMenuItem', label: 'select inverse', shortcut: '⌘⇧I', disabled: () => !s.hasSelection, onSelect: act('selectInverseMenuItem') },
                        { type: 'separator' },
                        { id: 'colorRangeMenuItem', label: 'color range...', onSelect: act('colorRangeMenuItem') },
                        { type: 'separator' },
                        { id: 'borderSelectionMenuItem', label: 'border...', disabled: () => !s.hasSelection, onSelect: act('borderSelectionMenuItem') },
                        { id: 'smoothSelectionMenuItem', label: 'smooth...', disabled: () => !s.hasSelection, onSelect: act('smoothSelectionMenuItem') },
                        { id: 'expandSelectionMenuItem', label: 'expand...', disabled: () => !s.hasSelection, onSelect: act('expandSelectionMenuItem') },
                        { id: 'contractSelectionMenuItem', label: 'contract...', disabled: () => !s.hasSelection, onSelect: act('contractSelectionMenuItem') },
                        { id: 'featherSelectionMenuItem', label: 'feather...', disabled: () => !s.hasSelection, onSelect: act('featherSelectionMenuItem') },
                    ],
                },
        {
            type: 'menu',
            id: 'filterMenu',
            trigger: { label: 'filter', id: 'filterMenuTitle' },
            items: [
                { type: 'submenu', classes: 'has-submenu', id: 'filterBlurTrigger', label: "blur", items: [
                    { label: "blur", attrs: { 'data-effect': 'filter/blur' }, onSelect: () => window.__parity.calls.push('effect:filter/blur') },
                    { label: "motion blur", attrs: { 'data-effect': 'filter/directionalBlur' }, onSelect: () => window.__parity.calls.push('effect:filter/directionalBlur') },
                    { label: "zoom blur", attrs: { 'data-effect': 'filter/zoomBlur' }, onSelect: () => window.__parity.calls.push('effect:filter/zoomBlur') },
                    { label: "spin blur", attrs: { 'data-effect': 'filter/spinBlur' }, onSelect: () => window.__parity.calls.push('effect:filter/spinBlur') },
                    { label: "median", attrs: { 'data-effect': 'filter/median' }, onSelect: () => window.__parity.calls.push('effect:filter/median') },
                    { label: "soft focus", attrs: { 'data-effect': 'filter/vaseline' }, onSelect: () => window.__parity.calls.push('effect:filter/vaseline') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterSharpenTrigger', label: "sharpen", items: [
                    { label: "sharpen", attrs: { 'data-effect': 'filter/sharpen' }, onSelect: () => window.__parity.calls.push('effect:filter/sharpen') },
                    { label: "unsharp mask", attrs: { 'data-effect': 'filter/unsharpMask' }, onSelect: () => window.__parity.calls.push('effect:filter/unsharpMask') },
                    { label: "high pass", attrs: { 'data-effect': 'filter/highPass' }, onSelect: () => window.__parity.calls.push('effect:filter/highPass') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterPixelateTrigger', label: "pixelate", items: [
                    { label: "pixelate", attrs: { 'data-effect': 'filter/pixels' }, onSelect: () => window.__parity.calls.push('effect:filter/pixels') },
                    { label: "halftone", attrs: { 'data-effect': 'filter/halftone' }, onSelect: () => window.__parity.calls.push('effect:filter/halftone') },
                    { label: "dither", attrs: { 'data-effect': 'filter/dither' }, onSelect: () => window.__parity.calls.push('effect:filter/dither') },
                    { label: "low poly", attrs: { 'data-effect': 'filter/lowPoly' }, onSelect: () => window.__parity.calls.push('effect:filter/lowPoly') },
                    { label: "glyph map", attrs: { 'data-effect': 'filter/glyphMap' }, onSelect: () => window.__parity.calls.push('effect:filter/glyphMap') },
                    { label: "stipple", attrs: { 'data-effect': 'filter/stipple' }, onSelect: () => window.__parity.calls.push('effect:filter/stipple') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterDistortTrigger', label: "distort", items: [
                    { label: "warp", attrs: { 'data-effect': 'filter/warp' }, onSelect: () => window.__parity.calls.push('effect:filter/warp') },
                    { label: "bulge", attrs: { 'data-effect': 'filter/bulge' }, onSelect: () => window.__parity.calls.push('effect:filter/bulge') },
                    { label: "pinch", attrs: { 'data-effect': 'filter/pinch' }, onSelect: () => window.__parity.calls.push('effect:filter/pinch') },
                    { label: "skew", attrs: { 'data-effect': 'filter/skew' }, onSelect: () => window.__parity.calls.push('effect:filter/skew') },
                    { label: "waves", attrs: { 'data-effect': 'filter/waves' }, onSelect: () => window.__parity.calls.push('effect:filter/waves') },
                    { label: "ripples", attrs: { 'data-effect': 'filter/pondRipples' }, onSelect: () => window.__parity.calls.push('effect:filter/pondRipples') },
                    { label: "twirl", attrs: { 'data-effect': 'filter/spiral' }, onSelect: () => window.__parity.calls.push('effect:filter/spiral') },
                    { label: "polar coordinates", attrs: { 'data-effect': 'filter/polar' }, onSelect: () => window.__parity.calls.push('effect:filter/polar') },
                    { label: "tunnel", attrs: { 'data-effect': 'filter/tunnel' }, onSelect: () => window.__parity.calls.push('effect:filter/tunnel') },
                    { label: "wormhole", attrs: { 'data-effect': 'filter/wormhole' }, onSelect: () => window.__parity.calls.push('effect:filter/wormhole') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterGlitchTrigger', label: "glitch", items: [
                    { label: "glitch", attrs: { 'data-effect': 'classicNoisedeck/glitch', 'data-params': "{\"glitchiness\":50,\"aberration\":30}" }, onSelect: () => window.__parity.calls.push('effect:classicNoisedeck/glitch') },
                    { label: "corrupt", attrs: { 'data-effect': 'filter/corrupt' }, onSelect: () => window.__parity.calls.push('effect:filter/corrupt') },
                    { label: "pixel sort", attrs: { 'data-effect': 'filter/pixelSort' }, onSelect: () => window.__parity.calls.push('effect:filter/pixelSort') },
                    { label: "scanline error", attrs: { 'data-effect': 'filter/scanlineError' }, onSelect: () => window.__parity.calls.push('effect:filter/scanlineError') },
                    { label: "crt", attrs: { 'data-effect': 'filter/crt' }, onSelect: () => window.__parity.calls.push('effect:filter/crt') },
                    { label: "tv snow", attrs: { 'data-effect': 'filter/snow' }, onSelect: () => window.__parity.calls.push('effect:filter/snow') },
                    { label: "degauss", attrs: { 'data-effect': 'filter/degauss' }, onSelect: () => window.__parity.calls.push('effect:filter/degauss') },
                    { label: "chromatic aberration", attrs: { 'data-effect': 'filter/chromaticAberration' }, onSelect: () => window.__parity.calls.push('effect:filter/chromaticAberration') },
                    { label: "feedback", attrs: { 'data-effect': 'filter/convolutionFeedback' }, onSelect: () => window.__parity.calls.push('effect:filter/convolutionFeedback') },
                    { label: "echo trails", attrs: { 'data-effect': 'filter/reverb' }, onSelect: () => window.__parity.calls.push('effect:filter/reverb') },
                    { label: "video feedback", attrs: { 'data-effect': 'filter/feedback', 'data-params': "{\"mix\":50,\"scaleAmt\":97,\"rotation\":2}" }, onSelect: () => window.__parity.calls.push('effect:filter/feedback') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterStylizeTrigger', label: "stylize", items: [
                    { label: "edge detect", attrs: { 'data-effect': 'filter/edge' }, onSelect: () => window.__parity.calls.push('effect:filter/edge') },
                    { label: "glowing edge", attrs: { 'data-effect': 'filter/glowingEdge' }, onSelect: () => window.__parity.calls.push('effect:filter/glowingEdge') },
                    { label: "emboss", attrs: { 'data-effect': 'filter/emboss' }, onSelect: () => window.__parity.calls.push('effect:filter/emboss') },
                    { label: "extrude", attrs: { 'data-effect': 'filter/extrude' }, onSelect: () => window.__parity.calls.push('effect:filter/extrude') },
                    { label: "cel shading", attrs: { 'data-effect': 'filter/celShading' }, onSelect: () => window.__parity.calls.push('effect:filter/celShading') },
                    { label: "oil paint", attrs: { 'data-effect': 'filter/oilPaint' }, onSelect: () => window.__parity.calls.push('effect:filter/oilPaint') },
                    { label: "wind", attrs: { 'data-effect': 'filter/wind' }, onSelect: () => window.__parity.calls.push('effect:filter/wind') },
                    { label: "scatter", attrs: { 'data-effect': 'filter/scatter' }, onSelect: () => window.__parity.calls.push('effect:filter/scatter') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterSketchTrigger', label: "sketch", items: [
                    { label: "chrome", attrs: { 'data-effect': 'filter/chrome' }, onSelect: () => window.__parity.calls.push('effect:filter/chrome') },
                    { label: "photocopy", attrs: { 'data-effect': 'filter/photocopy' }, onSelect: () => window.__parity.calls.push('effect:filter/photocopy') },
                    { label: "stamp", attrs: { 'data-effect': 'filter/stamp' }, onSelect: () => window.__parity.calls.push('effect:filter/stamp') },
                    { label: "relief", attrs: { 'data-effect': 'filter/relief' }, onSelect: () => window.__parity.calls.push('effect:filter/relief') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterBrushStrokesTrigger', label: "brush strokes", items: [
                    { label: "hatch", attrs: { 'data-effect': 'filter/hatch' }, onSelect: () => window.__parity.calls.push('effect:filter/hatch') },
                    { label: "strokes", attrs: { 'data-effect': 'filter/strokes' }, onSelect: () => window.__parity.calls.push('effect:filter/strokes') },
                    { label: "spatter", attrs: { 'data-effect': 'filter/spatter' }, onSelect: () => window.__parity.calls.push('effect:filter/spatter') },
                    { label: "outline", attrs: { 'data-effect': 'filter/outline' }, onSelect: () => window.__parity.calls.push('effect:filter/outline') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterArtisticTrigger', label: "artistic", items: [
                    { label: "watercolor", attrs: { 'data-effect': 'filter/watercolor' }, onSelect: () => window.__parity.calls.push('effect:filter/watercolor') },
                    { label: "plastic wrap", attrs: { 'data-effect': 'filter/plasticWrap' }, onSelect: () => window.__parity.calls.push('effect:filter/plasticWrap') },
                    { label: "historic palette", attrs: { 'data-effect': 'filter/historicPalette' }, onSelect: () => window.__parity.calls.push('effect:filter/historicPalette') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterTextureTrigger', label: "texture", items: [
                    { label: "grain", attrs: { 'data-effect': 'filter/grain' }, onSelect: () => window.__parity.calls.push('effect:filter/grain') },
                    { label: "craquelure", attrs: { 'data-effect': 'filter/craquelure' }, onSelect: () => window.__parity.calls.push('effect:filter/craquelure') },
                    { label: "mosaic tiles", attrs: { 'data-effect': 'filter/mosaicTiles' }, onSelect: () => window.__parity.calls.push('effect:filter/mosaicTiles') },
                    { label: "patchwork", attrs: { 'data-effect': 'filter/patchwork' }, onSelect: () => window.__parity.calls.push('effect:filter/patchwork') },
                    { label: "texturizer", attrs: { 'data-effect': 'filter/texture' }, onSelect: () => window.__parity.calls.push('effect:filter/texture') },
                    { label: "grime", attrs: { 'data-effect': 'filter/grime' }, onSelect: () => window.__parity.calls.push('effect:filter/grime') },
                    { label: "fibers", attrs: { 'data-effect': 'filter/fibers' }, onSelect: () => window.__parity.calls.push('effect:filter/fibers') },
                    { label: "scratches", attrs: { 'data-effect': 'filter/scratches' }, onSelect: () => window.__parity.calls.push('effect:filter/scratches') },
                    { label: "stray hair", attrs: { 'data-effect': 'filter/strayHair' }, onSelect: () => window.__parity.calls.push('effect:filter/strayHair') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterLightLensTrigger', label: "light & lens", items: [
                    { label: "bloom", attrs: { 'data-effect': 'filter/bloom' }, onSelect: () => window.__parity.calls.push('effect:filter/bloom') },
                    { label: "vignette", attrs: { 'data-effect': 'filter/vignette' }, onSelect: () => window.__parity.calls.push('effect:filter/vignette') },
                    { label: "lens flare", attrs: { 'data-effect': 'filter/lensFlare' }, onSelect: () => window.__parity.calls.push('effect:filter/lensFlare') },
                    { label: "light leak", attrs: { 'data-effect': 'filter/lightLeak' }, onSelect: () => window.__parity.calls.push('effect:filter/lightLeak') },
                    { label: "lighting", attrs: { 'data-effect': 'filter/lighting' }, onSelect: () => window.__parity.calls.push('effect:filter/lighting') },
                    { label: "lens distortion", attrs: { 'data-effect': 'filter/lens', 'data-params': "{\"displacement\":0.3}" }, onSelect: () => window.__parity.calls.push('effect:filter/lens') },
                    { label: "clouds", attrs: { 'data-effect': 'filter/clouds' }, onSelect: () => window.__parity.calls.push('effect:filter/clouds') },
                ] },
                { type: 'submenu', classes: 'has-submenu', id: 'filterTileTrigger', label: "tile", items: [
                    { label: "kaleidoscope", attrs: { 'data-effect': 'filter/tile' }, onSelect: () => window.__parity.calls.push('effect:filter/tile') },
                    { label: "repeat", attrs: { 'data-effect': 'filter/repeat' }, onSelect: () => window.__parity.calls.push('effect:filter/repeat') },
                    { label: "seamless", attrs: { 'data-effect': 'filter/seamless' }, onSelect: () => window.__parity.calls.push('effect:filter/seamless') },
                    { label: "flip mirror", attrs: { 'data-effect': 'filter/flipMirror' }, onSelect: () => window.__parity.calls.push('effect:filter/flipMirror') },
                ] },
                { type: 'separator' },
                { id: 'filterMoreMenuItem', label: 'more...', onSelect: act('filterMoreMenuItem') },
            ],
        },
                {
                    type: 'menu',
                    trigger: { label: 'view' },
                    items: [
                        { id: 'zoomInMenuItem', label: 'zoom in', onSelect: act('zoomInMenuItem') },
                        { id: 'zoomOutMenuItem', label: 'zoom out', onSelect: act('zoomOutMenuItem') },
                        { type: 'separator' },
                        { type: 'radio', id: 'fitInWindowMenuItem', label: 'fit in window', checked: () => s.zoom === 'fit', onSelect: () => { s.zoom = 'fit'; window.__parity.calls.push('fitInWindowMenuItem') } },
                        { type: 'separator' },
                        { type: 'radio', id: 'zoom50MenuItem', label: '50%', checked: () => s.zoom === '50', onSelect: () => { s.zoom = '50'; window.__parity.calls.push('zoom50MenuItem') } },
                        { type: 'radio', id: 'zoom100MenuItem', label: '100% (actual size)', checked: () => s.zoom === '100', onSelect: () => { s.zoom = '100'; window.__parity.calls.push('zoom100MenuItem') } },
                        { type: 'radio', id: 'zoom200MenuItem', label: '200%', checked: () => s.zoom === '200', onSelect: () => { s.zoom = '200'; window.__parity.calls.push('zoom200MenuItem') } },
                    ],
                },
            ],
            center: [],
            right: [
                { type: 'button', id: 'playPauseBtn', icon: () => s.playing ? 'pause' : 'play_arrow', attrs: { title: 'Play/Pause (Space)' }, ariaLabel: 'Play/Pause', onSelect: () => { s.playing = !s.playing; window.__parity.calls.push('playPauseBtn') } },
            ],
        },
    }
}
